# Site settings
title: Columbia Medicine Microscopy Core (MMC)
subtitle: (MMC)
email: jwm2175@cumc.columbia.edu
description: NONE
url: "https://www.columbia-mmc.org"
# url: "https://JWM-CU.github.io"
baseurl: ""
# baseurl: "/mmc3"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  John W Murray, PhD <br/>
  Imaging Facility Director <br/>
  Assistant Professor <br/>
  Columbia University <br/> 
  Department of Medicine <br/>
  Columbia Center for Human Development (CCHD) <br/>
  jwm2175©cumc•columbia•edu <br/>
  Office phone: 212•305•4130 <br/>

# location: >
#  William Black Building 8th Floor <br/> 
#  [William Black Building 8th Floor](https://www.google.com/maps/place/https://maps.app.goo.gl/ZrTUzCe3eAFwvyPf9)  (https://maps.app.goo.gl/ZrTUzCe3eAFwvyPf9) <br/> 
#  Room 828, 832, and VP&S 8-508B <br/>
#  Office: room 801F <br/>
#  650 West 168th Street <br/>
#  New York, NY 10032 <br/>

location: >
  William Black Building<br/> 
  <a href="https://maps.app.goo.gl/ZrTUzCe3eAFwvyPf9" target="_blank">(google maps link)</a> <br/> 
  8th Floor, Room 828, 832, and VP&S 8-508B <br/>
  Office: room 801F <br/>
  650 West 168th Street <br/>
  New York, NY 10032 <br/>


hours: >
  Hours: 24/7 <br/>
  Staffed: M-F, 9am-5pm <br/>

contact: >
   jwm2175©cumc•columbia•edu

# Pages shown in navbar
nav_pages:
  - name: about
  - name: stellaris
  - name: zeiss710
  - name: lightsheet
  - name: dmi-1-2
  - name: live-imaging
    name: seahorse
  - name: rates
  - name: software-resources
#  - name: publications

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll/scholar
  - jekyll-sitemap

scholar:

  last_name: Doeds
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
